* Consider the below code to answer further questions:

In [3]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

* List - A list in Python is an inbuilt collection of items that can contain elements of multiple data types, which may be either numeric, character logical values, etc. It is an ordered collection supporting negative indexing. A list can be created using [] containing data values. Contents of lists can be easily merged and copied using Python’s inbuilt functions. 

* Array - An array is a vector containing homogeneous elements i.e. belonging to the same data type. Elements are allocated with contiguous memory locations. Typically the size of an array is fixed. Th e insertion and deletion costs are high as compared to the list however indexing is faster in the Arrays due to contiguous memory allocation. Arrays can be used by importing the array module.

In [5]:
# Example of List
Sample_list = ['a' , 'Murtaza' , 23 , 23.4 , 2+23j , [1,23,3]]
print(type(Sample_list))
print(Sample_list)

<class 'list'>
['a', 'Murtaza', 23, 23.4, (2+23j), [1, 23, 3]]


In [11]:
# Example of array('i', [1, 2, 3])
import array as arr
a = arr.array('i', [1, 2, 3])
print(type(a))
for i in a:
    print(i, end=" ")

<class 'array.array'>
1 2 3 

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [20]:
list_ = [1, 2.0, "three", [4, 5], (6, 7)]
arra_list = [1, 2.0, "three", [4, 5], (6, 7)]

for i in list_:
    print(type(i))

for i in arra_list:
    print(type(i))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'tuple'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

* Yes, there will be a difference in the data type of the elements present in both the variables list_ and arra_list. The elements in list_ are of different data types such as integer, float, string, list and tuple. But when we convert it to an array of integers using np.array() function, all the elements will be converted to integers.

In [3]:
import numpy as np

list_ = [1, 2.0, "three", [4, 5], (6, 7)]
arra_list = [1, 2.0, "three", [4, 5], (6, 7)]

array_list = np.array(object = list_, dtype = int)

for i in list_:
    print(type(i))

for i in arra_list:
    print(type(i))

for i in array_list:
    print(type(i))



ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

* As we see i got an error while running this code because in list_ there are some float,tuple,str and ist inside it but we only use dtype = int so it show me error

* Consider the below code to answer further questions:

In [10]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [19]:
# (1) shape
np.shape(num_array)

(2, 3)

In [18]:
# (2) size
np.size(num_array)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [13]:
import numpy.matlib as nm
arr = nm.zeros((3,3))
arr

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [4]:
nm.eye(5,5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])